       commentByUid: user.uid,
       commentByName: user.name,
       commentByAvatar: user.avatar.url,
       comment: sanitize(comment.comment),
       viewers: CommentViewersService.viewers(comment, current_user),
       createdAt: created_at(comment.created_at),